steps:
  # Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Build
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: gcr.io/cloud-builders/gsutil
    args:
      ['-m', 'rsync', '-r', '-c', '-d', '-z', './public', 'gs://test-web-blog']
