steps:
  # Install
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  # Build
  - name: 'gcr.io/cloud-builders/npm'
    env:
      - 'NODE_ENV=production'
    args: ['run', 'build']
  - name: gcr.io/cloud-builders/gsutil
    args: ['-m', 'rsync', '-e', '-r', '-d', './public', 'gs://test-web-blog']
